### ISSUE TITLE
Internal error when trying to sign up as user

### ISSUE THREAD

**Issue by stefanfilm** [stefanfilm/WebWeaversJobSite#16]
<img width="990" alt="Screenshot 2024-07-17 at 6 16 24 PM" src="https://github.com/user-attachments/assets/fdac0d0d-7483-45ac-ab50-e2aba32ab8bc">

Hi @swe-thinhnguyen1701 I attached a screenshot of the error.

**Comment by swe-thinhnguyen1701** [comment]
can you tell me step by step when this error raise?

**Comment by stefanfilm** [comment]
I pulled code from github, I was already on the database, I did npm seed, I did node server.js. I went to sign up. I clicked sign up as user. I entered my information on the page: sai@mail.com stefan456 username, etc. Then the internal error popped up.

**Comment by swe-thinhnguyen1701** [comment]
ERROR fixed

**Comment by swe-thinhnguyen1701** [comment]
Error fixed.
