### ISSUE TITLE
Hamburger menu shows up behind content 

### ISSUE THREAD

**Issue by stefanfilm** [stefanfilm/WebWeaversJobSite#17]
I went to the create job post page as a recruiter and clicked on the hamburger menu. The menu appears behind he content on the page so it is unable to be seen. I included a screenshot here.
<img width="1403" alt="Screenshot 2024-07-17 at 6 22 39 PM" src="https://github.com/user-attachments/assets/8347a48c-4c66-44bb-93ba-cd828b1d5148">

**Comment by daimyo1** [comment]
fixed in new patch update
